# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 882d33dcbf5379f699894e5915b79f6c86b54a8d9aa1c9daab80f9104edb6398c88daa29aa6d7ef38888922f723df5e97e06620578c5fa94b273286a95116155

test:
  secret_key_base: 0d9330640fa3f27e583df901f60f5269fd7590d1f3a64f86b4c109644725c4bd3881a6e1790ec101a9b9e8167e1a140ceb1027a27161087725c8727fef7d4f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
