default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: ebay_clone_development

test:
  <<: *default
  adapter: postgresql
  database: ebay_clone_test

production:
  <<: *default
  database: ebay_clone_production
  username: ebay_clone
  password: <%= ENV['EBAY_CLONE_DATABASE_PASSWORD'] %>
