development:
  secret_key_base: 6794035de3a6b6f1a956e2ff96a6570bca6ee8ee7a77962fe4c8aa0be3eb5bf92fdffa13649d53e548571a89f7c93c2e239d675adabe0883cb0208230534ee53
  smtp_domain: <%= ENV["EBAY_CLONE_SMTP_DOMAIN"] %>
  smtp_user_name: <%= ENV["EBAY_CLONE_SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["EBAY_CLONE_SMTP_PASSWORD"] %>

test:
  secret_key_base: 0efdaaf685a41e9ea1ca5b69db74c9887d5922fe6ecf3a61eb091d9a991e8db9c432083b0f00286f98d3f441b3dfe58183839c06f15815988974322519771364
  smtp_domain: <%= ENV["EBAY_CLONE_SMTP_DOMAIN"] %>
  smtp_user_name: <%= ENV["EBAY_CLONE_SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["EBAY_CLONE_SMTP_PASSWORD"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_domain: <%= ENV["EBAY_CLONE_SMTP_DOMAIN"] %>
  smtp_user_name: <%= ENV["EBAY_CLONE_SMTP_USER_NAME"] %>
  smtp_password: <%= ENV["EBAY_CLONE_SMTP_PASSWORD"] %>
